name: .NET

on:
  workflow_dispatch:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Build
      run: msbuild m2-unpacker.sln
    
    - name: Publish build artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: m2-unpacker-debug
        path: m2-unpacker\bin\Debug\net48